### PR TITLE
Implemented new XML Transformation CommentOut. Implemented the corres…

### PR DESCRIPTION
**Pull request by mits-live**
…ponding UnitTest case.
It is not a bugfix for error in the original repository, it is a new feature which I desperately needed, when I was working on a DevOps project involving Sitecore WCMS.
My thought are:
- I'd like to share this functionality with the community, for the case someone else needs it. 
- I'd like to contribute to this project and to enricht it with my knowledge and skills, this way helping other fellow community members to have better capable XmlTransform at their disposal...

Many thanks and kind regards,
@mits-live.

### CODE REVIEW

**Comment by vijayrkn** [comment]
@mits-live Thank you for the PR. We will review it soon.

**Comment by vijayrkn** [comment]
@mits-live - Sorry for the delay in reviewing this. Can you please fix the merge conflict in the test?

**Comment by mits-live** [comment]
@vijayrkn - the merge conflict have been merged.

**Comment by mits-live** [comment]
@vijayrkn - could you please look at the branch? The conflict have been resolved and you should be able to merge it into the master-branch...

**Pull request merged**
